name: Trigger auto deployment for application

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/application-AutoDeployTrigger-f4be3137-fc6c-4392-beb5-caf1db85c6a7.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.APPLICATION_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APPLICATION_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APPLICATION_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: myregistrylzkgk76hhjhghjfze.azurecr.io
          registryUsername: ${{ secrets.APPLICATION_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.APPLICATION_REGISTRY_PASSWORD }}
          containerAppName: application
          resourceGroup: applications
          imageToBuild: myregistrylzkgk76hhjhghjfze.azurecr.io/application:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


