name: CI

env:
    DO_NOT_TRACK: '1'

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            HOME: /root
            POSTGRES_URL: postgresql://postgres:admin@postgres:5432/todo?schema=public
            POSTGRES_URL_NON_POOLING: postgresql://postgres:admin@postgres:5432/todo?schema=public
            NEXTAUTH_SECRET: test-secret-ci-insecure
        services:
            postgres:
                image: postgres:16.3
                ports:
                    - '5432:5432'
                env:
                    POSTGRES_DB: todo
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: admin
        container:
            image: mcr.microsoft.com/playwright:v1.44.1-jammy
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: 'npm'
            - run: npm ci
            - run: npm run build
            - run: npm run db:push
            - run: npx vitest run
            - run: npm run test:e2e
