name: CI

env:
    DO_NOT_TRACK: '1'

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: mcr.microsoft.com/playwright:v1.44.1-jammy
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: 'npm'
            - run: npm ci
            - run: npm run build
            - run: npx vitest run
            - run: npm run test:e2e
              env:
                HOME: /root
